2021-03-16 14:07:04,157 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 14:07:14,546 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 14:34:49,212 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 15:16:49,361 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 15:29:40,191 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 16:29:26,371 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 16:29:29,302 ERROR: Exception on /index [GET] [in /Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/app/routes.py", line 22, in index
    return render_template("index.html", title='Home Page', form=form,
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/nkrizskiy/PycharmProjects/microblog123/app/templates/base.html", line 18, in top-level template code
    <a href="{{ url_for('explore') }}">Explore</a>
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2021-03-16 16:30:35,205 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 16:59:36,921 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:47]
2021-03-16 17:50:27,008 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:49]
2021-03-16 17:58:28,628 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:49]
2021-03-16 18:33:24,624 INFO: Microblog startup [in /Users/nkrizskiy/PycharmProjects/microblog123/app/__init__.py:49]
2021-03-16 18:37:49,612 ERROR: Exception on /reset_password_request [POST] [in /Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/app/routes.py", line 167, in reset_password_request
    send_password_reset_email(user)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/app/email.py", line 18, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/nkrizskiy/PycharmProjects/microblog123/myvenv/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
